"""Change relationships

Revision ID: cd76d8f710c5
Revises: 3f827a8266f9
Create Date: 2022-09-10 16:25:28.400786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd76d8f710c5'
down_revision = '3f827a8266f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
